modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="apocalypse"
version="1.0.0"
displayName="apocalypse"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="sampa, MCreator"

[[dependencies.apocalypse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



